---
- name: Backup Mikrotik
  hosts: routers
  gather_facts: true
  vars:
    backup_dir: "/tmp"
  tasks:
    - name: Export
      ansible.builtin.shell: >-
                sshpass -p '{{ ansible_password }}' ssh -o StrictHostKeyChecking=no {{ ansible_user }}@{{ inventory_hostname }} /export
      register: export

   - name: Backup
      ansible.builtin.copy:
        content: "{{ export.stdout }}"
        dest: "{{ backup_dir }}/{{ inventory_hostname }}_config.{{ lookup('pipe', 'date +%Y-%m-%d@%H:%M:%S') }}"
      when: export is defined
