
---
- hosts: all
  gather_facts: false
  tasks:

  - name: Run the backup command
    routeros_command:
      commands:
        - "/system backup save name="{{ inventory_hostname }}.config" dont-encrypt=yes"

  - name: Save backup to local file
    ansible.builtin.copy:
      src: "/{{ inventory_hostname }}.config"
      dest: "$HOME/{{ inventory_hostname }}.config"
    delegate_to: localhost

#  - name: Delete the backup file on the router
#    routeros_command:
#      commands:
#        - "/file remove [/file find name="{{ inventory_hostname }}.config"]"
