
---
- hosts: all
  gather_facts: false
  tasks:

  - name: Run the backup command
    routeros_command:
      commands:
        - "/system backup save name={{ inventory_hostname }} dont-encrypt=yes"

  - name: Save the backup command
    routeros_command:
      commands:
        - "tool fetch address=192.168.128.82 src-path={{ inventory_hostname }}.backup mode=ftp upload=yes user=solis password=teste123 dst-path={{ inventory_hostname }}.backup"


  - name: Delete the backup file on the router
    routeros_command:
      commands:
        - "/file remove [/file find name={{ inventory_hostname }}.backup]"
